version: '2'

services:
  magic-sync:
    image: mickaelperrin/docker-magic-sync:latest
    build: ../
    environment:
#    - SYNC_USER=www-data
    - SYNC_UID=33
    - SYNC_IGNORE=.idea:.git
    #- MAXIMUM_INOTIFY_WATCHES=524288
    volumes:
    # Configure here the mappings between your host and the container.
    # Simply add a `.magic` extension to the volume path in the container.
    - ..:/src.magic
    # this is needed for automatic discovery of mounted volumes in this container.
    - /var/run/docker.sock:/tmp/docker.sock:ro
    # If you want to configure USER / UID / IGNORE by volumes, you can use a simple YAML configuration file
    # - ./docker-syncs.yml:/sync-entrypoint.d/docker-syncs.yml
    volumes_from:
    - app
    # Privilegied mode is needed if you want to increase the maximum inotify watches for very large synced folders
    # by setting the ENV var MAXIMUM_INOTIFY_WATCHES.
    #privileged: true
