version: '2'

services:
  magic-sync:
    privileged: true
    image: mickaelperrin/docker-unison-fswatch:latest
    environment:
    - SYNC_USER=www-data
    - SYNC_UID=33
    - SYNC_IGNORE=" -ignore 'Path */.idea/' -ignore 'Path */.git/' "
    volumes:
    - ./src:/src.magic
    - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
    - app
